// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Propely.PropertiesApi.Infrastructure.Persistence;

#nullable disable

namespace Propely.PropertiesApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305181511_AddPropertyMedia")]
    partial class AddPropertyMedia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Propely.PropertiesApi.Application.Common.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid")
                        .HasColumnName("causation_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("idx_outbox_unprocessed")
                        .HasFilter("processed_at_utc IS NULL");

                    b.ToTable("outbox_messages", null, t =>
                        {
                            t.HasCheckConstraint("chk_event_type", "event_type <> ''");
                        });
                });

            modelBuilder.Entity("Propely.PropertiesApi.Domain.Properties.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operation_type");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("property_type");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("video_url");

                    b.Property<string>("VirtualTourUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("virtual_tour_url");

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .HasDatabaseName("ix_properties_agent_id");

                    b.HasIndex("PropertyType")
                        .HasDatabaseName("ix_properties_property_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_properties_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_properties_tenant_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_properties_tenant_status");

                    b.ToTable("properties", (string)null);
                });

            modelBuilder.Entity("Propely.PropertiesApi.Domain.Properties.PropertyMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("media_type");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("property_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_path");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("thumbnail_path");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at_utc");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_property_media_tenant");

                    b.HasIndex("PropertyId", "TenantId")
                        .HasDatabaseName("ix_property_media_property_tenant");

                    b.ToTable("property_media", (string)null);
                });

            modelBuilder.Entity("Propely.PropertiesApi.Infrastructure.Persistence.Entities.ProcessedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("EventId");

                    b.HasIndex("EventType");

                    b.ToTable("processed_events", (string)null);
                });

            modelBuilder.Entity("Propely.PropertiesApi.Domain.Properties.Property", b =>
                {
                    b.OwnsOne("Propely.PropertiesApi.Domain.Properties.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("address_country");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("address_latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("address_longitude");

                            b1.Property<string>("MunicipalityCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("address_municipality_code");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Province")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_province");

                            b1.Property<string>("ProvinceCode")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("address_province_code");

                            b1.Property<string>("Street")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("address_street");

                            b1.HasKey("PropertyId");

                            b1.ToTable("properties");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.OwnsOne("Propely.PropertiesApi.Domain.Properties.ValueObjects.LocalizedText", "Description", b1 =>
                        {
                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("De")
                                .HasMaxLength(10000)
                                .HasColumnType("character varying(10000)")
                                .HasColumnName("description_de");

                            b1.Property<string>("En")
                                .HasMaxLength(10000)
                                .HasColumnType("character varying(10000)")
                                .HasColumnName("description_en");

                            b1.Property<string>("Es")
                                .HasMaxLength(10000)
                                .HasColumnType("character varying(10000)")
                                .HasColumnName("description_es");

                            b1.Property<string>("Fr")
                                .HasMaxLength(10000)
                                .HasColumnType("character varying(10000)")
                                .HasColumnName("description_fr");

                            b1.Property<string>("Nl")
                                .HasMaxLength(10000)
                                .HasColumnType("character varying(10000)")
                                .HasColumnName("description_nl");

                            b1.Property<string>("Pt")
                                .HasMaxLength(10000)
                                .HasColumnType("character varying(10000)")
                                .HasColumnName("description_pt");

                            b1.HasKey("PropertyId");

                            b1.ToTable("properties");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.OwnsOne("Propely.PropertiesApi.Domain.Properties.ValueObjects.PropertyFeatures", "Features", b1 =>
                        {
                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AirConditioning")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("features_air_conditioning");

                            b1.Property<int?>("Bathrooms")
                                .HasColumnType("integer")
                                .HasColumnName("features_bathrooms");

                            b1.Property<int?>("Bedrooms")
                                .HasColumnType("integer")
                                .HasColumnName("features_bedrooms");

                            b1.Property<decimal?>("BuiltArea")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("features_built_area");

                            b1.Property<decimal?>("EnergyConsumption")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("features_energy_consumption");

                            b1.Property<decimal?>("EnergyEmissions")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("features_energy_emissions");

                            b1.Property<string>("EnergyRating")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("features_energy_rating");

                            b1.Property<int?>("Floor")
                                .HasColumnType("integer")
                                .HasColumnName("features_floor");

                            b1.Property<bool>("Furnished")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("features_furnished");

                            b1.Property<bool>("HasElevator")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("features_has_elevator");

                            b1.Property<bool>("HasGarage")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("features_has_garage");

                            b1.Property<bool>("HasGarden")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("features_has_garden");

                            b1.Property<bool>("HasPool")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("features_has_pool");

                            b1.Property<bool>("HasTerrace")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("features_has_terrace");

                            b1.Property<bool>("Heating")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("features_heating");

                            b1.Property<string>("Orientation")
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("features_orientation");

                            b1.Property<int?>("ParkingSpaces")
                                .HasColumnType("integer")
                                .HasColumnName("features_parking_spaces");

                            b1.Property<decimal?>("PlotArea")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("features_plot_area");

                            b1.Property<decimal?>("UsableArea")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("features_usable_area");

                            b1.Property<int?>("YearBuilt")
                                .HasColumnType("integer")
                                .HasColumnName("features_year_built");

                            b1.HasKey("PropertyId");

                            b1.ToTable("properties");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.OwnsOne("Propely.PropertiesApi.Domain.Properties.ValueObjects.PropertyFinancials", "Financials", b1 =>
                        {
                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CatastroReference")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("financials_catastro_reference");

                            b1.Property<decimal?>("CommunityFees")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("financials_community_fees");

                            b1.Property<decimal?>("IbiTax")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("financials_ibi_tax");

                            b1.Property<decimal?>("Price")
                                .HasPrecision(14, 2)
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("financials_price");

                            b1.HasKey("PropertyId");

                            b1.ToTable("properties");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Description");

                    b.Navigation("Features");

                    b.Navigation("Financials");
                });
#pragma warning restore 612, 618
        }
    }
}
