// Copyright (c) 2026 Propely. All rights reserved.
// Licensed under the Proprietary Software License. See LICENSE.

namespace Propely.AiApi.Domain.Suggestions;

/// <summary>
/// Represents a proactive business suggestion generated by the rule engine.
/// Suggestions are computed on-demand from live data — no database persistence needed.
/// </summary>
public sealed record Suggestion(
    SuggestionType Type,
    SuggestionPriority Priority,
    string Message,
    string? ActionUrl = null,
    string? ActionLabel = null);
